import { Hono } from "hono";
import type { Env } from "../types";
import { requireAuth } from "../lib/auth";

export const agentRoutes = new Hono<{ Bindings: Env }>();
agentRoutes.use("*", requireAuth());

agentRoutes.get("/schema", (c) =>
  c.json({
    name: "bh-crm",
    version: 1,
    auth: "Authorization: Bearer <AGENT_API_KEY> — full parity with the human UI",
    conventions: {
      stages: ["new", "contacted", "quoted", "scheduled", "customer", "lost"],
      phones: "E.164 (+1XXXXXXXXXX)",
      timestamps: "ISO-8601 UTC",
    },
    endpoints: [
      { method: "GET", path: "/api/health", description: "Liveness check (public)" },
      { method: "POST", path: "/api/lead", description: "Public lead capture (CORS-gated). Body: {name, phone, email, vehicle, message?, source, source_detail, ts, website}" },
      { method: "GET", path: "/api/book/availability", description: "Public: open slots for ?date=YYYY-MM-DD. Returns {slots (UTC ISO), slot_min}" },
      { method: "POST", path: "/api/book", description: "Public self-booking. Body {name, phone, email?, service, address?, slot_start, ts, website}. Creates scheduled job; 409 slot_taken" },
      { method: "OPTIONS", path: "/api/lead", description: "CORS preflight for the public lead endpoint" },
      { method: "POST", path: "/api/auth/login", description: "Body {password} -> session cookie" },
      { method: "POST", path: "/api/auth/logout", description: "Clears the session cookie" },
      { method: "GET", path: "/api/contacts", description: "List. Query: search, stage, source, tag, limit (<=200), offset. Returns {items, total}" },
      { method: "POST", path: "/api/contacts", description: "Create. Body: {first_name?, last_name?, email?, phone?, address?, city?, stage?, source?, tags?, custom?}" },
      { method: "GET", path: "/api/contacts/:id", description: "Full contact + vehicles + parsed tags/custom" },
      { method: "PATCH", path: "/api/contacts/:id", description: "Partial update; custom shallow-merges; stage change logs stage_changed" },
      { method: "DELETE", path: "/api/contacts/:id", description: "Delete contact (cascades vehicles/activities)" },
      { method: "GET", path: "/api/contacts/:id/activities", description: "Timeline, newest first, limit 100" },
      { method: "POST", path: "/api/contacts/:id/activities", description: "Log manual touch. Body {type: note|call_logged|sms_logged, title, payload?}" },
      { method: "POST", path: "/api/contacts/bulk", description: "Import up to 200. Body {contacts:[...]} -> {created, merged, errors}" },
      { method: "POST", path: "/api/contacts/bulk-action", description: "Apply an op to many contacts. Body {ids:[], op: add_label|remove_label|set_stage|enroll_sequence, value}" },
      { method: "GET", path: "/api/labels", description: "List colored labels (double as email lists)" },
      { method: "POST", path: "/api/labels", description: "Create label {key, label, color?}" },
      { method: "PATCH", path: "/api/labels/:key", description: "Update label {label?, color?, sort?}" },
      { method: "DELETE", path: "/api/labels/:key", description: "Delete label; strips it from all contacts' tags" },
      { method: "GET", path: "/api/custom-fields", description: "List custom field definitions" },
      { method: "POST", path: "/api/custom-fields", description: "Body {key, label, type: text|number|select|date|checkbox, options?, sort?}" },
      { method: "DELETE", path: "/api/custom-fields/:key", description: "Remove a custom field definition" },
      { method: "GET", path: "/api/stats", description: "{byStage, recent} dashboard numbers" },
      { method: "GET", path: "/api/jobs", description: "List jobs. Query: status, contact_id, from, to (YYYY-MM-DD), limit, offset. Returns {items, total} with contact name/phone" },
      { method: "POST", path: "/api/jobs", description: "Create job. Body {contact_id, title, services?, price_cents?, status?, scheduled_start?, scheduled_end?, address?, notes?}" },
      { method: "GET", path: "/api/jobs/:id", description: "Job + contact + parsed services" },
      { method: "PATCH", path: "/api/jobs/:id", description: "Update job; status change logs job_status_changed, scheduling logs job_scheduled" },
      { method: "DELETE", path: "/api/jobs/:id", description: "Delete a job" },
      { method: "POST", path: "/api/jobs/:id/confirm", description: "Send booking confirmation email to the contact (log-only until Resend configured); stamps confirmation_sent_at" },
      { method: "POST", path: "/api/jobs/:id/request-review", description: "Send SMS+email review request with settings.review_url. 400 if review_url unset. Auto-sends on status->completed when settings.review_auto=1" },
      { method: "GET", path: "/api/tasks", description: "List tasks. Query: status (open|done|dismissed), contact_id, due_before. Returns {items}" },
      { method: "POST", path: "/api/tasks", description: "Create task. Body {title, contact_id?, job_id?, notes?, due_at?}" },
      { method: "PATCH", path: "/api/tasks/:id", description: "Update task; status=done stamps done_at" },
      { method: "DELETE", path: "/api/tasks/:id", description: "Delete a task" },
      { method: "GET", path: "/api/messages", description: "SMS thread for a contact. Query: contact_id (required), limit. Ascending. Returns {items}" },
      { method: "POST", path: "/api/messages", description: "Send SMS to a contact. Body {contact_id, body}. Logs sms_logged, advances new->contacted. Log-only until Twilio configured" },
      { method: "GET", path: "/api/messages/inbox", description: "Latest SMS per contact, newest first. Returns {items}" },
      { method: "POST", path: "/api/contacts/:id/touch", description: "Log a bridge tap-to-text/call. Body {channel: sms|call}. Logs activity, advances new->contacted" },
      { method: "GET", path: "/api/sequences", description: "List email nurture sequences with step/active counts" },
      { method: "POST", path: "/api/sequences", description: "Create sequence. Body {name, trigger?, steps?:[{delay_hours, subject, body_text}]}. trigger: manual|stage:new" },
      { method: "GET", path: "/api/sequences/:id", description: "Sequence + ordered steps" },
      { method: "PATCH", path: "/api/sequences/:id", description: "Update {name?, status: draft|active, trigger?, steps?} (steps replace all)" },
      { method: "DELETE", path: "/api/sequences/:id", description: "Delete a sequence" },
      { method: "POST", path: "/api/sequences/:id/enroll", description: "Enroll a contact. Body {contact_id}. Emails send on the cron, log-only until Resend set" },
      { method: "GET", path: "/api/sequences/:id/enrollments", description: "Enrollments for a sequence" },
      { method: "POST", path: "/api/ai/draft", description: "AI-draft an SMS/email for a contact. Body {contact_id, channel: sms|email}. 503 if ANTHROPIC_API_KEY unset" },
      { method: "GET", path: "/api/ai/digest", description: "Weekly digest: {stats, narrative}. narrative null until Anthropic key set. Lead intelligence auto-runs on capture" },
      { method: "GET", path: "/api/agent/schema", description: "This document" },
    ],
  })
);
